apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o4y7rpwdi-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-5d798856b5.swbu.p3.openshiftapps.com/rhtap/rhtap-qe:79aa332a05e608091da70312573e913c409309e6@sha256:1473159a2843d21fb6d73065b2252083d4668c868c5ecbe1b16dbf5d08839017
          name: container-image
